### ISSUE TITLE
Использование сторонних библиотек

### ISSUE THREAD

**Issue by AlexanderBodnya** [mermakova/soulbot#2]
А нужно ли использовать сторонние либы типа telegram? Имхо они тебя ограничивают и заставляют тратить время на их изучение. Я бы обошелся там где можно стандартными модулями.

**Comment by AlexanderBodnya** [comment]
Тем более, что для наших целей достаточно будет простых вещей, которые легко реализовать. По опыту использования сторонних модулей периодически возникает какая-то труднообъяснимая херня, от которой тяжело избавиться

**Comment by mermakova** [comment]
Что ты имеешь ввиду под стандартными модулями? Например, во взаимодействии с телеграмом. В начале у нас не будет сложного взаимодействия с API телеграма, это так, но впоследствии будет. Всякие кнопки меню для модераторов, например. Если ты имеешь ввиду, что мы сами можем написать обертки и обработчики ручек телеграма, то да, можем, но быстрее будет использовать готовое решение, но риски есть, да.
